from typing import Protocol, runtime_checkable


@runtime_checkable
class ContentBase(Protocol):
    def __lt__(self, other, /) -> bool: ...
    def __le__(self, other, /) -> bool: ...
    def __gt__(self, other, /) -> bool: ...
    def __ge__(self, other, /) -> bool: ...
    def __eq__(self, other, /) -> bool: ...
    def __bool__(self) -> bool: ...
