from typing import Protocol


class BatchToolsPort(Protocol):
    def prepare(self) -> None: ...

    def succeeded(self) -> bool: ...

    @property
    def mcp_config_path(self) -> str: ...

    def start(self) -> None: ...

    def stop(self) -> None: ...
