from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from claude_parser.application.pipeline_state import PipelineState
    from claude_parser.domain.node import Node, TreeDict


class StatePort(Protocol):
    def load_state(self) -> PipelineState | None: ...
    def save_state(self, state: PipelineState) -> None: ...
    def load_tree(self) -> tuple[Node, TreeDict] | None: ...
    def save_tree(self, root: Node) -> None: ...
    def tree_exists(self) -> bool: ...
