from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from claude_parser.application.pipeline_state import PipelineState
    from claude_parser.domain.node import Node, TreeDict


class StatePort(Protocol):
    # Pipeline state
    def load_state(self) -> PipelineState | None: ...
    def save_state(self, state: PipelineState) -> None: ...

    # Tree
    def load_tree(self) -> tuple[Node, TreeDict] | None: ...
    def save_tree(self, root: Node) -> None: ...
    def tree_exists(self) -> bool: ...

    # Directory setup
    def init_dirs(self) -> None: ...

    # Raw batches
    def write_raw_batch(self, batch_num: int, content: str) -> None: ...
    def resolve_raw_path(self, batch_num: int) -> str: ...

    # Clean batches
    def resolve_clean_path(self, batch_num: int) -> str: ...
    def clean_batch_exists(self, batch_num: int) -> bool: ...
    def read_clean_batch(self, batch_num: int) -> str | None: ...
    def read_all_clean_before_cutoff(self) -> str: ...

    # Logs and failures
    def write_log(self, chunk_id: str, content: str) -> None: ...
    def write_failure(self, chunk_id: str, content: str) -> None: ...

    # Memory
    def read_memory(self) -> str: ...

    # Context
    def get_context_lines(self, batch_num: int, n_lines: int) -> str: ...

    # Final output
    def write_final(self, content: str) -> None: ...
