from typing import Protocol
from claude_parser.domain.node import Node, TreeDict


class TreeRepositoryPort(Protocol):
    def load(self) -> tuple[Node, TreeDict] | None: ...
    def save(self, root: Node) -> None: ...
    def exists(self) -> bool: ...
